AllCops:
  Exclude:
    - vendor/**/*
    - pkg/**/*
    - spec/fixtures/**/*

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 328

# dealbreaker:
Style/TrailingComma:
  Enabled: false
Style/ClosingParenthesisIndentation:
  Enabled: false

# we still support ruby 1.8
Style/HashSyntax:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: true
Style/RegexpLiteral:
  Enabled: true
Style/WordArray:
  Enabled: true

# this catches the cases of using `module` for parser functions, types, or
# providers
Style/ClassAndModuleChildren:
  Enabled: false
