---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 3.3.0"
  - PUPPET_GEM_VERSION="~> 3.4.0"
  - PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 3.7.0" FUTURE_PARSER=yes
notifications:
  email:
    - merritt@krakowitzer.com
script: bundle exec rake test
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "NEEDHELPHERE"
  on:
    tags: true
    # all_branches is required to use tags
   all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
